"""GUI-owned persistence helpers for bounded procedures source blocks."""

from __future__ import annotations

import ast
import keyword
import os
import tempfile


BEGIN_MARKER = "# --- Hyde Window Macros: BEGIN ---"
END_MARKER = "# --- Hyde Window Macros: END ---"
BEGIN_FIT_FUNCTIONS_MARKER = "# --- Hyde Fit Functions: BEGIN ---"
END_FIT_FUNCTIONS_MARKER = "# --- Hyde Fit Functions: END ---"


class MacroStoreError(ValueError):
    """Raised when window-macro persistence input is invalid."""


def validate_macro_name(name):
    candidate = (name or "").strip()
    if not candidate:
        raise MacroStoreError("A macro name is required.")
    if not candidate.isidentifier() or keyword.iskeyword(candidate):
        raise MacroStoreError("Macro names must be valid Python identifiers.")
    return candidate


def _node_start_lineno(node):
    starts = [node.lineno]
    starts.extend(
        getattr(decorator, "lineno", node.lineno) for decorator in node.decorator_list
    )
    return min(starts)


def _find_marker_bounds(lines, begin_marker, end_marker):
    begin = end = None
    for index, line in enumerate(lines):
        stripped = line.rstrip("\n")
        if stripped == begin_marker:
            begin = index
        elif stripped == end_marker:
            end = index
    if begin is None or end is None or begin >= end:
        return None
    return begin, end


def _ensure_marker_block(text, begin_marker, end_marker):
    lines = text.splitlines(keepends=True)
    bounds = _find_marker_bounds(lines, begin_marker, end_marker)
    if bounds is not None:
        return text

    if text and not text.endswith("\n"):
        text += "\n"
    if text and not text.endswith("\n\n"):
        text += "\n"
    text += f"{begin_marker}\n{end_marker}\n"
    return text


def _top_level_function_matches(text, name):
    try:
        tree = ast.parse(text or "")
    except SyntaxError:
        return []

    matches = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == name:
            matches.append(
                {
                    "name": name,
                    "start_lineno": _node_start_lineno(node),
                    "end_lineno": node.end_lineno,
                }
            )
    return matches


def inspect_bounded_conflict(path, name, begin_marker, end_marker):
    candidate = validate_macro_name(name)
    if not os.path.exists(path):
        return None

    with open(path, "r", encoding="utf-8") as handle:
        text = handle.read()

    matches = _top_level_function_matches(text, candidate)
    if not matches:
        return None

    lines = text.splitlines(keepends=True)
    bounds = _find_marker_bounds(lines, begin_marker, end_marker)
    conflicts = []
    for match in matches:
        conflict = dict(match)
        conflict["multiple_matches"] = len(matches) > 1
        if bounds is None:
            conflict["in_autogenerated_block"] = False
        else:
            begin, end = bounds
            conflict["in_autogenerated_block"] = begin < conflict["start_lineno"] - 1 < end
        conflicts.append(conflict)
    for conflict in conflicts:
        if not conflict["in_autogenerated_block"]:
            return conflict
    return conflicts[-1]


def inspect_macro_conflict(path, name):
    return inspect_bounded_conflict(path, name, BEGIN_MARKER, END_MARKER)


def inspect_fit_function_conflict(path, name):
    return inspect_bounded_conflict(
        path,
        name,
        BEGIN_FIT_FUNCTIONS_MARKER,
        END_FIT_FUNCTIONS_MARKER,
    )


def _bounded_matches(text, name, begin_marker, end_marker):
    lines = text.splitlines(keepends=True)
    bounds = _find_marker_bounds(lines, begin_marker, end_marker)
    if bounds is None:
        return []

    begin, end = bounds
    return [
        match
        for match in _top_level_function_matches(text, name)
        if begin < match["start_lineno"] - 1 < end
    ]


def _replace_bounded_matches(
    text,
    matches,
    replacement,
    *,
    begin_marker,
    end_marker,
):
    if not matches:
        return _insert_into_bounded_block(
            text,
            replacement,
            begin_marker=begin_marker,
            end_marker=end_marker,
        )

    lines = text.splitlines(keepends=True)
    insertion_index = min(match["start_lineno"] for match in matches) - 1
    for match in sorted(matches, key=lambda item: item["start_lineno"], reverse=True):
        del lines[match["start_lineno"] - 1 : match["end_lineno"]]
    lines[insertion_index:insertion_index] = [replacement.rstrip() + "\n\n"]
    return "".join(lines)


def _insert_into_bounded_block(text, replacement, *, begin_marker, end_marker):
    normalized = _ensure_marker_block(text, begin_marker, end_marker)
    lines = normalized.splitlines(keepends=True)
    begin, end = _find_marker_bounds(lines, begin_marker, end_marker)
    del begin
    insertion = replacement.rstrip() + "\n\n"
    return "".join(lines[:end] + [insertion] + lines[end:])


def update_bounded_source(path, name, definition_source, begin_marker, end_marker):
    candidate = validate_macro_name(name)
    text = ""
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as handle:
            text = handle.read()

    conflict = inspect_bounded_conflict(path, candidate, begin_marker, end_marker)
    if conflict is not None:
        if not conflict.get("in_autogenerated_block", False):
            raise MacroStoreError(
                f"{candidate} already exists outside Hyde's autogenerated window-macro block."
            )
        updated = _replace_bounded_matches(
            text,
            _bounded_matches(text, candidate, begin_marker, end_marker),
            definition_source,
            begin_marker=begin_marker,
            end_marker=end_marker,
        )
    else:
        updated = _insert_into_bounded_block(
            text,
            definition_source,
            begin_marker=begin_marker,
            end_marker=end_marker,
        )
    return updated


def update_macro_source(path, name, macro_source):
    return update_bounded_source(path, name, macro_source, BEGIN_MARKER, END_MARKER)


def update_fit_function_source(path, name, function_source):
    return update_bounded_source(
        path,
        name,
        function_source,
        BEGIN_FIT_FUNCTIONS_MARKER,
        END_FIT_FUNCTIONS_MARKER,
    )


def write_bounded_source(path, name, definition_source, begin_marker, end_marker):
    updated = update_bounded_source(
        path,
        name,
        definition_source,
        begin_marker,
        end_marker,
    )
    directory = os.path.dirname(path)
    os.makedirs(directory, exist_ok=True)
    fd, temp_path = tempfile.mkstemp(
        prefix="hyde-macros-",
        suffix=".py",
        dir=directory,
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(updated)
        os.replace(temp_path, path)
    finally:
        if os.path.exists(temp_path):
            os.unlink(temp_path)
    return updated


def write_macro_source(path, name, macro_source):
    return write_bounded_source(path, name, macro_source, BEGIN_MARKER, END_MARKER)


def write_fit_function_source(path, name, function_source):
    return write_bounded_source(
        path,
        name,
        function_source,
        BEGIN_FIT_FUNCTIONS_MARKER,
        END_FIT_FUNCTIONS_MARKER,
    )
