from __future__ import annotations

from qtutils.qt import QtWidgets

from hyde.user_interface.base_hyde_widgets import HydePromptDialog
from hyde.user_interface.shared.plugin import HydePlugin
from hyde.user_interface.shared.project import (
    MacroStoreError,
    inspect_macro_conflict,
    write_macro_source,
)


class SaveWindowDialog(HydePromptDialog):
    SAVE = 1
    NO_SAVE = 2
    CANCEL = 0

    def __init__(self, saveable, parent=None):
        super().__init__(parent=parent)
        self.choice = self.CANCEL
        self.saveable = saveable
        self.load_ui("save_window_dialog.ui", module_name=__name__)

        self.ui.nameEdit.setText(self.saveable.default_macro_name())
        self.ui.nameEdit.selectAll()
        self.ui.saveButton.clicked.connect(self._accept_save)
        self.ui.noSaveButton.clicked.connect(self._accept_no_save)
        self.ui.cancelButton.clicked.connect(self.reject)
        self.ui.helpButton.clicked.connect(self._show_help)

    def macro_name(self):
        return self.ui.nameEdit.text().strip()

    def macro_source(self):
        return self.saveable.macro_source(self.macro_name())

    def _accept_save(self):
        self.choice = self.SAVE
        self.accept()

    def _accept_no_save(self):
        self.choice = self.NO_SAVE
        self.accept()

    def _show_help(self):
        QtWidgets.QMessageBox.information(
            self,
            "Window Recreation Macros",
            "Save stores a recreation macro in procedures/__init__.py.\n\n"
            "No Save closes the window without writing a macro.\n\n"
            "Cancel leaves the window open.",
        )


class SaveWindowDialogService:
    def prompt_to_save_window_macro(self, *, saveable):
        parent = saveable if isinstance(saveable, QtWidgets.QWidget) else None
        saveable_service = getattr(saveable, "service", None)
        procedures_service = (
            None
            if not callable(saveable_service)
            else saveable_service("project_procedures_service")
        )
        while True:
            dialog = SaveWindowDialog(saveable=saveable, parent=parent)
            if dialog.exec_() != QtWidgets.QDialog.Accepted:
                return False
            if dialog.choice == SaveWindowDialog.NO_SAVE:
                return True
            if dialog.choice != SaveWindowDialog.SAVE:
                return False

            macro_name = dialog.macro_name()
            try:
                macro_source = dialog.macro_source()
            except MacroStoreError as exc:
                QtWidgets.QMessageBox.warning(parent, "Invalid Macro Name", str(exc))
                continue

            procedures_init = (
                None
                if procedures_service is None
                else procedures_service.procedures_init()
            )
            if not procedures_init:
                QtWidgets.QMessageBox.warning(
                    parent,
                    "Unable To Save Macro",
                    "Window recreation macros require an active project procedures/__init__.py path.",
                )
                continue

            conflict = inspect_macro_conflict(procedures_init, macro_name)
            if conflict is not None:
                if not conflict.get("in_autogenerated_block", False):
                    QtWidgets.QMessageBox.warning(
                        parent,
                        "Macro Name In Use",
                        f"{macro_name} already exists outside Hyde's autogenerated window-macro block.\n\n"
                        "Choose a different macro name.",
                    )
                    continue
                response = QtWidgets.QMessageBox.question(
                    parent,
                    "Overwrite Recreation Macro",
                    f"A function named {macro_name} already exists in procedures/__init__.py.\n\n"
                    "Overwrite that function?",
                    QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
                    QtWidgets.QMessageBox.No,
                )
                if response != QtWidgets.QMessageBox.Yes:
                    continue

            try:
                write_macro_source(procedures_init, macro_name, macro_source)
            except MacroStoreError as exc:
                QtWidgets.QMessageBox.warning(parent, "Unable To Save Macro", str(exc))
                continue
            procedures_service.reload_procedures()
            return True


class Plugin(HydePlugin):
    def __init__(self, initial_settings):
        super().__init__(initial_settings)
        self.save_window_dialog_service = SaveWindowDialogService()

    def get_services(self):
        return {"save_window_dialog_service": self.save_window_dialog_service}
