"""GUI-owned persistence helpers for saved table recreation macros."""

from __future__ import annotations

import ast
import keyword
import os
import tempfile


BEGIN_MARKER = "# --- Hyde Window Macros: BEGIN ---"
END_MARKER = "# --- Hyde Window Macros: END ---"


class MacroStoreError(ValueError):
    """Raised when window-macro persistence input is invalid."""


def validate_macro_name(name):
    candidate = (name or "").strip()
    if not candidate:
        raise MacroStoreError("A macro name is required.")
    if not candidate.isidentifier() or keyword.iskeyword(candidate):
        raise MacroStoreError("Macro names must be valid Python identifiers.")
    return candidate


def _node_start_lineno(node):
    starts = [node.lineno]
    starts.extend(
        getattr(decorator, "lineno", node.lineno) for decorator in node.decorator_list
    )
    return min(starts)


def _find_marker_bounds(lines):
    begin = end = None
    for index, line in enumerate(lines):
        stripped = line.rstrip("\n")
        if stripped == BEGIN_MARKER:
            begin = index
        elif stripped == END_MARKER:
            end = index
    if begin is None or end is None or begin >= end:
        return None
    return begin, end


def _ensure_macro_block(text):
    lines = text.splitlines(keepends=True)
    bounds = _find_marker_bounds(lines)
    if bounds is not None:
        return text

    if text and not text.endswith("\n"):
        text += "\n"
    if text and not text.endswith("\n\n"):
        text += "\n"
    text += f"{BEGIN_MARKER}\n{END_MARKER}\n"
    return text


def _top_level_function_matches(text, name):
    try:
        tree = ast.parse(text or "")
    except SyntaxError:
        return []

    matches = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == name:
            matches.append(
                {
                    "name": name,
                    "start_lineno": _node_start_lineno(node),
                    "end_lineno": node.end_lineno,
                }
            )
    return matches


def inspect_macro_conflict(path, name):
    candidate = validate_macro_name(name)
    if not os.path.exists(path):
        return None

    with open(path, "r", encoding="utf-8") as handle:
        text = handle.read()

    matches = _top_level_function_matches(text, candidate)
    if not matches:
        return None

    lines = text.splitlines(keepends=True)
    bounds = _find_marker_bounds(lines)
    conflicts = []
    for match in matches:
        conflict = dict(match)
        conflict["multiple_matches"] = len(matches) > 1
        if bounds is None:
            conflict["in_autogenerated_block"] = False
        else:
            begin, end = bounds
            conflict["in_autogenerated_block"] = begin < conflict["start_lineno"] - 1 < end
        conflicts.append(conflict)
    for conflict in conflicts:
        if not conflict["in_autogenerated_block"]:
            return conflict
    return conflicts[-1]


def _autogenerated_matches(text, name):
    lines = text.splitlines(keepends=True)
    bounds = _find_marker_bounds(lines)
    if bounds is None:
        return []

    begin, end = bounds
    return [
        match
        for match in _top_level_function_matches(text, name)
        if begin < match["start_lineno"] - 1 < end
    ]


def _replace_autogenerated_matches(text, matches, replacement):
    if not matches:
        return _insert_into_autogenerated_block(text, replacement)

    lines = text.splitlines(keepends=True)
    insertion_index = min(match["start_lineno"] for match in matches) - 1
    for match in sorted(matches, key=lambda item: item["start_lineno"], reverse=True):
        del lines[match["start_lineno"] - 1 : match["end_lineno"]]
    lines[insertion_index:insertion_index] = [replacement.rstrip() + "\n\n"]
    return "".join(lines)


def _insert_into_autogenerated_block(text, replacement):
    normalized = _ensure_macro_block(text)
    lines = normalized.splitlines(keepends=True)
    begin, end = _find_marker_bounds(lines)
    del begin
    insertion = replacement.rstrip() + "\n\n"
    return "".join(lines[:end] + [insertion] + lines[end:])


def update_macro_source(path, name, macro_source):
    candidate = validate_macro_name(name)
    text = ""
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as handle:
            text = handle.read()

    conflict = inspect_macro_conflict(path, candidate)
    if conflict is not None:
        if not conflict.get("in_autogenerated_block", False):
            raise MacroStoreError(
                f"{candidate} already exists outside Hyde's autogenerated window-macro block."
            )
        updated = _replace_autogenerated_matches(
            text,
            _autogenerated_matches(text, candidate),
            macro_source,
        )
    else:
        updated = _insert_into_autogenerated_block(text, macro_source)
    return updated


def write_macro_source(path, name, macro_source):
    updated = update_macro_source(path, name, macro_source)
    directory = os.path.dirname(path)
    os.makedirs(directory, exist_ok=True)
    fd, temp_path = tempfile.mkstemp(
        prefix="hyde-macros-",
        suffix=".py",
        dir=directory,
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(updated)
        os.replace(temp_path, path)
    finally:
        if os.path.exists(temp_path):
            os.unlink(temp_path)
    return updated
